# 2018-12-12 (cc) <paul4hough@gmail.com>
#
---
- need:
  why: is it needed?
  who: will be effected?
  what: is needed?
  how: to measure success?
  do: satisfy the need!

- integrated workflow:
  - develop communication
  - develop tests
  - develop objects
  - iterate
