# 2018-12-21 (cc) <paul4hough@gmail.com>
#
---
global:
  # How frequently to scrape targets by default.
  # scrape_interval: <duration> | default = 1m ]

  # How long until a scrape request times out.
  # [ scrape_timeout: <duration> | default = 10s ]

  # How frequently to evaluate rules.
  # [ evaluation_interval: <duration> | default = 1m ]

  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #   [ <labelname>: <labelvalue> ... ]

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
# rule_files:
#   [ - <filepath_glob> ... ]

scrape_configs:
  # linux node_exporter
  - job_name: linux
    scrape_interval: 1m
    scrape_timeout:  1m
    file_sd_configs:
      - jobs/linux-nodes.yml

  # process_exporter watching george
  - job_name: proc-george
    scrape_interval: 10m
    scrape_timeout:  10m
    file_sd_configs:
      - jobs/george-proc-nodes.yml

  # postgresql_exporter
  - job_name: postgresql
    scrape_interval: 5m
    scrape_timeout:  5m
    file_sd_configs:
      - jobs/postgresql-nodes.yml

  # jmx_exporter watching tomcat servers
  - job_name: jmx-tomcat
    scrape_interval: 15s
    scrape_timeout:  30s
    file_sd_configs:
      - jobs/tomcat-jmx-nodes.yml

  # grok_exporter watching tomcat servers
  - job_name: jmx-tomcat
    scrape_interval: 15s
    scrape_timeout:  30s
    file_sd_configs:
      - jobs/tomcat-logs-nodes.yml

# A list of scrape configurations.
# scrape_configs:
#   [ - <scrape_config> ... ]

# The job name assigned to scraped metrics by default.
# - job_name: <job_name>

  # How frequently to scrape targets from this job.
  # [ scrape_interval: <duration> | default = <global_config.scrape_interval> ]

  # Per-scrape timeout when scraping this job.
  # [ scrape_timeout: <duration> | default = <global_config.scrape_timeout> ]

  # The HTTP resource path on which to fetch metrics from targets.
  # [ metrics_path: <path> | default = /metrics ]

  # honor_labels controls how Prometheus handles conflicts between labels
  # [ honor_labels: <boolean> | default = false ]

  # Configures the protocol scheme used for requests.
  # [ scheme: <scheme> | default = http ]

  # Optional HTTP URL parameters.
  # params:
  #   [ <string>: [<string>, ...] ]

  # Sets the `Authorization` header on every scrape request with the
  # configured username and password.
  # password and password_file are mutually exclusive.
  # basic_auth:
  #   [ username: <string> ]
  #   [ password: <secret> ]
  #   [ password_file: <string> ]

  # Sets the `Authorization` header on every scrape request with
  # the configured bearer token. It is mutually exclusive with
  # `bearer_token_file`.
  # [ bearer_token: <secret> ]

  # Sets the `Authorization` header on every scrape request with
  # the bearer token read from the configured file. It is mutually exclusive
  # with `bearer_token`.
  # [ bearer_token_file: /path/to/bearer/token/file ]

  # Configures the scrape request's TLS settings.
  # tls_config:
  #   [ <tls_config> ]

  # Optional proxy URL.
  # [ proxy_url: <string> ]

  # List of Azure service discovery configurations.
  # azure_sd_configs:
  #   [ - <azure_sd_config> ... ]

  # List of Consul service discovery configurations.
  # consul_sd_configs:
  #   [ - <consul_sd_config> ... ]

  # List of DNS service discovery configurations.
  # dns_sd_configs:
  #   [ - <dns_sd_config> ... ]

  # List of EC2 service discovery configurations.
  # ec2_sd_configs:
  #   [ - <ec2_sd_config> ... ]

  # List of OpenStack service discovery configurations.
  # openstack_sd_configs:
  #   [ - <openstack_sd_config> ... ]

  # List of file service discovery configurations.
  # file_sd_configs:
  #   [ - <file_sd_config> ... ]

  # List of GCE service discovery configurations.
  # gce_sd_configs:
  #   [ - <gce_sd_config> ... ]

  # List of Kubernetes service discovery configurations.
  # kubernetes_sd_configs:
  #   [ - <kubernetes_sd_config> ... ]

  # List of Marathon service discovery configurations.
  # marathon_sd_configs:
  #   [ - <marathon_sd_config> ... ]

  # List of AirBnB's Nerve service discovery configurations.
  # nerve_sd_configs:
  #   [ - <nerve_sd_config> ... ]

  # List of Zookeeper Serverset service discovery configurations.
  # serverset_sd_configs:
  #   [ - <serverset_sd_config> ... ]

  # List of Triton service discovery configurations.
  # triton_sd_configs:
  #   [ - <triton_sd_config> ... ]

  # List of labeled statically configured targets for this job.
  # static_configs:
  #   [ - <static_config> ... ]

  # List of target relabel configurations.
  # relabel_configs:
  #   [ - <relabel_config> ... ]

  # List of metric relabel configurations.
  # metric_relabel_configs:
  #   [ - <relabel_config> ... ]

  # Per-scrape limit on number of scraped samples that will be accepted.
  # If more than this number of samples are present after metric relabelling
  # the entire scrape will be treated as failed. 0 means no limit.
  # [ sample_limit: <int> | default = 0 ]

# Alerting specifies settings related to the Alertmanager.
# alerting:
#   alert_relabel_configs:
#     [ - <relabel_config> ... ]
#   alertmanagers:
#     [ - <alertmanager_config> ... ]

# Settings related to the remote write feature.
# remote_write:
#   [ - <remote_write> ... ]

# # Settings related to the remote read feature.
# remote_read:
#   [ - <remote_read> ... ]
